### ISSUE TITLE
Catmul-Rom Spline Orient to Path

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#1008]
I seem to have broken the Catmul-Rom spline orientation with I believe the Quaternion rewrite.

**Comment by NiciDieNase** [comment]
This issue does not seem to be completely fixed.
I'm using Catmu-Rom-Splines for an animtion with no repetition (RepeatMode.NONE), OrientToPath set to true and a path that is not closed.
At the end of the Path the object gets flipped around to face backwards.

This seems to be caused by the fact that near the end of the path calculatePoint() returns points the object has already passed. So lookAt lets the object face backwards instead of forwards.

**Comment by NiciDieNase** [comment]
I think this issue should be reopend.  @jwoolston @MasDennis 

My workaround works for my usecase, I'm not sure if it breaks anything else.
