### ISSUE TITLE
Comparing on adding a textures and Materials could be wrong.

### ISSUE THREAD

**Issue by semenoh** [Rajawali/Rajawali#1227]
I'm experiencing `OpenGL Error: out of memory 1285` similar to this one https://github.com/MasDennis/Rajawali/issues/1138 except the fact I'm do not use `RajawaliiActivity` nor `RojawaliFragment`. While I've been debugging this issue I'v met some strange things in the code. For instance:

`MaterialManager.addMaterial()` method contains next code:

```Java
for(Material mat : mMaterialList) {
	if(mat == material)
		return material;
}
```

but `mat == material` will not work here.

Also `TextureManager.addTask()` method contains code:

```Java
if (mTextureList.get(i) != texture)
	texture.setFrom(mTextureList.get(i));
else
	return;
```

`mTextureList.get(i) != texture` here also would not work.

Also if you repalce it with `!mTextureList.get(i).equals(texture)` it will work only if it is the same instance (has the same address in the memory) but if you created the another instance of the same texture it will not work as `equals(Object o)` isn't overridden properly in `ATexture`, `Texture`, `Material` classes.

BTW it should be overridden in order to figure out if `List<Material>` or `List<Texture>` already contains this material/texture...

**Comment by jwoolston** [comment]
I took a look into this more and I think I have some revelations to share. What @MasDennis wrote is correct and functioning properly, and here is why:

When adding a texture, we first check if any textures by the same name exist already. If they don't, the addition is pretty straight forward. Now if a texture by the same name does exist, we check if it is the same object using the `!=` operator. And in this case it is not incorrect because we are literally interested in if it is the same object or not. If it is, we don't need to do anything, we have already added it. If it is not the same, we make the following assumption: The user is trying to use a different object to refer to the same texture. The same argument follows for materials. In this case, it is important to remember that textures are uniquely identified by name only in Rajawali.

I am updating the docs to reflect the above.
