### ISSUE TITLE
Children of Object3D are not pickable with ObjectColorPicker

### ISSUE THREAD

**Issue by C0br4** [Rajawali/Rajawali#1387]
When a child of an `Object3D` is registered in an `ObjectColorPicker`, it can't be picked. 
As aworkaround I remove the child from its parent `Object3D` and add it to the `RajawaliScene` directly which weirdly works.

**Comment by jwoolston** [comment]
This is probably because child objects arent exactly treated the same from the standpoint of uniqueness. I would assume off hand that touching child or root objects would result in the root being chosen - not sure that that is what happens either though.

**Comment by C0br4** [comment]
@jwoolston The `onObjectPicked()` from the corresponding Listener is never called.

**Comment by jwoolston** [comment]
@MasDennis do you have any input on this?

**Comment by MasDennis** [comment]
I'll investigate

**Comment by rpicolet** [comment]
I forked a repo in order to fix this (and a couple of other minor problems).  I got things working for my use cases, but the scope of the changes - while not huge - was not trivial either, and right in the heart of all the rendering logic (modified Material.java, Object3D.java, ObjectColorPicker,java, and RajawaliScene,java).  I am quite willing to submit a pull request if someone on the team has time to review/test my changes against other use cases, but I don't want to claim I understand the risks...

**Comment by jwoolston** [comment]
@rpicolet If you have a branch with a clean set of changes to fix this I can take a look, just submit a PR and I should be able to pull the code locally.

**Comment by rpicolet** [comment]
PR coming soon. I will document my concerns there.  Thanks!

**Comment by jwoolston** [comment]
Should be resolved as of #1614
