### ISSUE TITLE
Rajawali imported obj with mtl textures .. fade animation?

### ISSUE THREAD

**Issue by jychimaster** [Rajawali/Rajawali#1431]
I imported an obj model with textures defined in an mtl file in Rajawali.
I would love to be able to do a fade animation much in the same way with ColorAnimation controlling the color and alpha channels.

Is there a way to do this with png texture imported models?
Is there any technique at all to fade a png textured model manipulating the alpha channels the same way with color? I was able to make some head-way manipulating the RGB values with setMaterialColor but it doesn't seem to accomplish anything with alpha.

**Comment by jwoolston** [comment]
In order to be rendered with an alpha channel, you must call `setTransparent(true)` on the object. As far as having the texture transparency, you texture must support it. A PNG can, but only if it was created with an alpha channel. Finally, the `ColorAnimation3D` applies to vertex colors which wont have any effect on the texture colors. You would have to write a custom material shader to do this.

**Comment by jwoolston** [comment]
Closing issue as abandoned/resolved.
