### ISSUE TITLE
SkyBox mirror problem

### ISSUE THREAD

**Issue by uzman** [Rajawali/Rajawali#1445]
Hi,
i am using your framework for panorama photos.
getCurrentScene().setSkybox(R.drawable.posx3, R.drawable.negx3,
R.drawable.posy3, R.drawable.negy3, R.drawable.posz3,
R.drawable.negz3);

but it mirrors the images. i mean all the writings on the buildings (in photos) are reversed.

any help please?

**Comment by jwoolston** [comment]
Looking into this it appears to be a bug. Normally a cube map is used external, but a skymap is looking at the inside of the cubemap, which mirrors the images. The material shader for skymaps is supposed to take care of this by automirroring for you but it seems this is failing. We'll look into it.

**Comment by jwoolston** [comment]
After some further thought, this is going to depend on the images as well. Many skybox images are already mirrored to account for the different view point because of the way they are created. Im not sure we should do anything about this. A better solution might just be to require the images to be mirrored prior to coming in.

**Comment by jwoolston** [comment]
They are in fact mirrored. Comparing the skybox images to the website they came from they appear to be backwards.
