### ISSUE TITLE
RajawaliScene.updateSkybox() does not change texture.

### ISSUE THREAD

**Issue by uzman** [Rajawali/Rajawali#1448]
## Underlying bug

`getCurrentScene().updateSkybox(posx, negx, posy, negy, posz, negz);` does not update the skybox texture.

## Original support Request
Hi,
i wanted to change skybox images at runtime with a timer.
before i set skybox i use clear() method. I'm not sure if it is true.
				getCurrentScene().clear();

but after 3. skybox images, it gives OutOfMemory. (when i try all images one by one  it is ok.)
but when i change it with timer it crashes.

is it logical to change skybox at runtime? what do you advise? how can i solve it?

**Comment by jwoolston** [comment]
The clear method is not what you want. It is supposed to wipe out everything from the scene and is intended to be used sparingly. There is nothing wrong with changing the skybox at runtime. If you are hitting an OOM error after three boxes, it means your textures must be absolutely massive. What is the resolution of your image?

**Comment by uzman** [comment]
i have 5 skybox images.
they are 1.5 MB around. is it big for skybox? if yes, what is the max size to run better?

when i set skybox with new images, does it remove the old one?

**Comment by MasDennis** [comment]
This is how you replace the bitmap to update a texture:
```
mTexture.setBitmap(myNewBitmap);
TextureManager.getInstance().replaceTexture(mTexture);
```
Remember to `recycle()` the bitmap after this.

**Comment by uzman** [comment]
@MasDennis 
i think you misunderstood.
I'm changing the skybox image.
			getCurrentScene().setSkybox(posx, negx, posy, negy, posz, negz);

**Comment by MasDennis** [comment]
Have you tried this?
```
getCurrentScene().updateSkybox(posx, negx, posy, negy, posz, negz);
```

**Comment by uzman** [comment]
yes, i tried it.  no crash - no OOM.
but it doesn't change the skybox image.

**Comment by MasDennis** [comment]
I'm going to have to take a closer look at this after I finish my current tasks.

**Comment by uzman** [comment]
thanks.

by the way;
i am using this version : https://github.com/Rajawali/RajawaliVR
last commit is 9 months before.
but Rajawali framework is newer. 
is the problem related with it?

**Comment by uzman** [comment]
Changing the skybox is very urgent. deadline is wednesday.
is there any progress.
i scaled down the images 700x700 px.
a skybox image (6 images) size is about : 650 KB - 900 KB
i set it; getCurrentScene().setSkybox(posx, negx, posy, negy, posz, negz);

but it still crashes. OutOfMemory.
can you help?

thanks...

**Comment by jwoolston** [comment]
> Changing the skybox is very urgent. deadline is wednesday.

Your deadline is not our deadline. We have day jobs that are not Rajawali. Progress happens when we have free time, and we often prioritize our development tasks over support requests. I can confirm that the texture update with `updateSkybox` does not work as it should. Beyond that, you will have to wait until we get to it.

**Comment by jwoolston** [comment]
The problem here is due to the replace method of `CubemapTexture` being empty. See [here](https://github.com/Rajawali/Rajawali/blob/master/rajawali/src/main/java/org/rajawali3d/materials/textures/CubeMapTexture.java#L163)

**Comment by uzman** [comment]
@jwoolston thanks for your help.
i don't want to interrupt your works. if it is possible to correct  updateSkybox method easily (i don't want to take your time much), i can pay it via PayPal. it is very urgent.
or i will wait and fail.

thanks in advance...

**Comment by MasDennis** [comment]
There is an official donation page. https://pledgie.com/campaigns/21807

**Comment by jwoolston** [comment]
@uzman There is no need for payment. Honestly it is more trouble than its worth and i wouldn't feel right profiting off of your situation. I will re-arrange my schedule and take a look at it today. I dont know what time zone you are in but hopefully it will make a difference. If you are still feeling like paying, you can contribute to our pledgie campaign linked from the readme or above. 

On a more personal note, its generally not a good idea to use a library's development branch for a project with a deadline, especially when you do not understand the underlying technology. If for whatever you find that you must use it, when you create support tickets you should strive to provide as much information as possible, as clearly as possible. Your tickets have been very sparse, and include no debug information such as stack traces or code which reproduces the error for us to go from. This tends to make the ticket a very low priority for us to handle. Furthermore, either because of language barrier or otherwise, your requests come across as demanding, especially when telling us about your deadlines. Answers were provided to some of your other questions which you initially rejected, but due to lack of information up front, we were not able to determine the true nature of the problem you were having, causing it to take longer to resolve. In the end, we are happy to help, but you need to help us help you first. 

That said, I will do my best to resolve this issue quickly today.

**Comment by uzman** [comment]
thanks. timezone is +2.
my project will not be published in playstore. 
it is an inline demonstration but very important. the app will be installed some android phones.
it will be used in a big presentation during 4 days.
i think i can use development branch. if updating skybox is ok (no OOM), thats all.

thank you very much.

**Comment by jwoolston** [comment]
@uzman  Its fixed. Just keep in mind that a skybox is 6 textures. It will be very easy to run out of graphics memory if you use large ones. Texture compression and minimum resolution which shows the  required level of detail are essential. The examples app can switch between 1024x1024 textures easily on a Nexus 5. Older devices not so well.
