### ISSUE TITLE
The Final Review (Anchor Steam)

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#1470]
The final review is a last look at everything before we release the code. We are less interested in fixing all known bugs (they will be handled later and we still want to know about new ones). Our primary focus here is to look over the API and make sure it is something we are ok with being stable. In particular, this is the time to remove something. Comment as you see fit. This issue will stay open while I work on updating the docs and preparing the other repositories for using the 1.0 release.

**Comment by jwoolston** [comment]
Cross referencing #1471 #1732 for history.

**Comment by jayschwa** [comment]
Is there a web page generated from the Javadoc anywhere?

**Comment by ToxicBakery** [comment]
No, but that would be a good feature request for 1.1

**Comment by dcerisano** [comment]
I have run AS through APPTHWACK concentrating on Samsung/Android5+.
You really should replace any mention of the word "stable" with "pre-alpha".

**Comment by MasDennis** [comment]
Hi Dominic,
Would you care to elaborate?
We could use some help testing the framework (and fixing it of course).

**Comment by dcerisano** [comment]
I will not be held responsible for the continued claim that any part of this project has ever been stable.

Github is a source of free software, not just free testing.

**Comment by MasDennis** [comment]
Hi Dominic,

I think there is a misunderstanding here.
Testing is absolutely on our radar. We just haven't had the time to do it yet. Some of us have had children recently and we have very busy day jobs.

We try to put a lot of features into the framework that people want. Many people love the framework and many people have contributed.

You're not seeing any leadership because we have very busy lives. We try to squeeze in a bit of Rajawali every now and then because we love working on it and we love open source. But the reality is that we don't always have the time for it.

I don't see how you can possibly be offended by my polite request for help. I am not demanding anything.
I love it when people contribute and I am grateful for the effort people have made in the past. 

I am not quite sure if you appreciate the effort that goes into building a framework like Rajawali. Sure, it doesn't come anywhere near Unreal Engine (which is not our goal anyway) but we spent years building this framework. Mostly for others to use. At least one core Rajawali developer hasn't even used the framework to build an app himself while some users have made thousands of dollars by using Rajawali for their live wallpapers.

Trolling this issue isn't constructive. It is also something I don't appreciate.

Best,
Dennis

**Comment by dcerisano** [comment]
Do you insult of your contributors by calling them "Trolls"?

The owners of this project have clearly and publicly stated that this project is "stable" but also that "testing is really not on our radar". I am sure you can at least appreciate this contradiction.

**Comment by MasDennis** [comment]
Hi Dominic,

I do not wish to offend but your tone is slightly aggressive. Try to not get things the wrong way.

I appreciate your past contributions and I appreciate your suggestions about cloud testing. Just like the (subtantial) contributions of so many other people.

@jwoolston 's comment was not about testing in general. It was about the specific cloud testing platform you mentioned. One of our next objectives is setting up unit tests. That should've been a part of the framework already but we never had the time to add those.
We do want cloud testing at some point. It is not on our radar because we already have so many things to do. Writing unit tests for instance.

Lets not fight about words but lets try to focus on what the purpose of this issue is: make this version of Rajawali better and test the hell out of it. It is a community framework and everybody is invited to help.

Dennis

**Comment by dcerisano** [comment]
Thanks very much for the recognition and commitment to the value of testing.

Happy to provide continued leadership in this area.

**Comment by MasDennis** [comment]
You're welcome to contribute to unit testing. It will really improve the stability of the framework.

**Comment by dcerisano** [comment]
The Testing Cloud will be available "later this summer". Let's circle back then.

My efforts with AppThwack have indicated that the primary source of instability is Open GL/ES, and the way different manufacturers support it.

To be stable, any Open GL/ES project (like this one) will need to provide all the required work-arounds for all device/os versions.

Google itself has caused this by making app devs responible for device/os stability and are now providing free cloud testing to achieve it.

**Comment by MasDennis** [comment]
Interesting. You're welcome to fix those issues :beers: Sound like you're aware of what those issues are.

**Comment by dcerisano** [comment]
I am getting my head kicked in by Samsung owners who have upgraded to Android-L.
The tread marks on my scalp all read "Open GL/ES".
