### ISSUE TITLE
Please publish testing results before using the word "stable" to describe any build.

### ISSUE THREAD

**Issue by dcerisano** [Rajawali/Rajawali#1510]
Google is launching a new cloud testing lab this summer. Please use it and post the results.

I am currently using Appthwack but it is expensive, slow and does not support the use of the word "stable" for any build tested.

https://docs.google.com/forms/d/1CKdq-rkcZ_ixmTcUgq21xURDijBsf8uF7w7hvlgUmpo/viewform

**Comment by jwoolston** [comment]
Please write the testing and we will be happy to do so. Its not really on our radar at the moment.

**Comment by dcerisano** [comment]
If you kept up to date on Android you would know there are no testing cases required.
Just run your example app on the cloud and post the results.

**Comment by dcerisano** [comment]
Received confirmation from @MasDennis that testing IS on your radar.
Closing this issue.

**Comment by MasDennis** [comment]
Well, slightly outside of our radar due to a lack of time. We want formal testing but we haven't gotten there yet.
We are dedicated to the quality of this framework. @jwoolston is a very well respected member of the Rajawali team and has made significant contributions. Family is on his radar at the moment which is of course much more important than anything else :v:

**Comment by dcerisano** [comment]
Whatever.
To be absolutely and finally clear, I will never submit any testing results to this project without a consistent commitment, which I am certainly not seeing.

**Comment by MasDennis** [comment]
I can't believe you just said that.

**Comment by dcerisano** [comment]
I cant believe that you can commit to something on one thread and then uncommit to it on another.
