### ISSUE TITLE
Mysterious errors in logcat perhaps culprits for random rendering errors

### ISSUE THREAD

**Issue by adamantivm** [Rajawali/Rajawali#1517]
While tracking down why sometimes my renderer fails and leaves a half-completed scene, I noticed that we consistently have these errors shown in the logcat whenever we modify the scene:

```
06-18 11:13:45.354 E/Rajawali(15849): Getting location of uniform: uNormalMatrix returned -1!
06-18 11:13:45.364 E/Rajawali(15849): Getting location of uniform: uModelMatrix returned -1!
06-18 11:13:45.364 E/Rajawali(15849): Getting location of uniform: uModelViewMatrix returned -1!
06-18 11:13:45.364 E/Rajawali(15849): Getting location of uniform: uTime returned -1!
```

I can see one instance of the text above per Object3D that I add. Anyone knows what this is about?

I'm using Rajawali 1.0.258-SNAPSHOT although I see the same when using master. Any hint is appreciated.

**Comment by adamantivm** [comment]
@abhinshekBansal I saw you reported seeing the same messages when trying some of the examples. Did you find any additional information about this?

**Comment by adamantivm** [comment]
#1498 may be related

**Comment by jwoolston** [comment]
It looks like the material was not properly configured. You said this is from modifying the scene after rendering has started? In that case it is possible there is still a bug in how the material detects changes.

**Comment by adamantivm** [comment]
@jwoolston thanks for your answer. We may indeed be doing something wrong with the materials, in which case we would very greatly appreciate guidance on how to do it better.

Our approach is as follows: in ```onRender``` if any of our data objects have changed, we do something like this:

```
getCurrentScene().clearChildren();
for( each data object ) {
    Object3D myObject = new MyObject3D(data);
    getCurrentScene().addChild(myObject);
}
```

Where ```MyObject3D``` is a simple subclass of ```Object3D``` which like so:

```
public class MyObject3D extends Object3D {
    Plane plane;
    RectangularPrism prism;

    public MyObject3D(some data) {
        plane = new Plane(1, 1, 24, 24);
        plane.setMaterial(new Material());
        plane.setPosition(data.pos);
        plane.setRotation(data.rot);
        plane.setColor(Color.GRAY);
        plane.setAlpha(0.5f);

        prism = new RectangularPrism(0.01f, 0.01f, 0.5f);
        prism.setMaterial(new Material());
        prism.setPosition(data.pos);
        prism.setOrientation(data.rot);
        prism.setColor(Color.GREEN);
        prism.setAlpha(0.25f);
        prism.moveForward(0.25f);

        super.addChild(plane);
        super.addChild(prism);
    }
}
```

**Comment by jwoolston** [comment]
I suspect what is happening here is you are overloading the OpenGL driver/chipset with the number of materials you are creating. When you remove the object in `onRender()`, their data still exists from the point of view of the GL context, and then you immediately create more. Since it appears your materials are not changing in their actual source, but rather the uniforms being passed to them, I would suggest simply modifying the material instead of removing the object, creating a new one and creating a new material. This will not only (I think) resolve your issue, but it will also be *MUCH* faster as the cost of creating a new material is very high (it requires a shader program to be compiled and queries to be made against it which completely halts the rendering pipeline). Furthermore, creating new objects has a high cost as their VBOs must be created and pushed to the GPU. Uniforms on the other hand are expected to be passed to the GPU in each frame. To this end,  the entire system is designed to make this fast so changing things in the material such as color, object position, etc are ultra fast without requiring the shader program to be changed.

Times where you would want to create a new material would include things such as changing the lighting effects (specular/diffuse methods, reflectivity, etc), adding or removing textures (not changing them), changing texture type (i.e. normal map to diffuse map, etc).

**Comment by adamantivm** [comment]
@jwoolston thank you very much for the explanation. We are moving towards a model where we create the objects once and then only update their position, color, etc.

I am noticing though that even in that case we get the errors described at the top of the issue when the objects are initially created. Is there anything missing in our material creation process that could be generating those errors?

We moved to using Rajawali from sources without any different results.

**Comment by ToxicBakery** [comment]
I'm fairly confident those errors are erroneous and are actually just info, not errors. Your shader does not contain those uniform values so the Rajawali Shader system is just warning you that it can not pass those values in.

**Comment by adamantivm** [comment]
@ToxicBakery thank you for your input. If that is indeed the case then this issue can be closed satisfactorily.
