### ISSUE TITLE
Unfortunate MD5 loading time

### ISSUE THREAD

**Issue by Tritaru** [Rajawali/Rajawali#1540]
I have a wallpaper ready for release, if not for one tiny issue. I have three skeletally animated MD5 models, each handcrafted to be as low-poly as possible. Despite this, parsing these three assets constitutes >90% of the loading time for my wallpaper in logcat. The two smaller ones each take ~0.5 seconds to load, according to logcat. Unfortunately, adding the largest one (600 poly's) takes 2.3 seconds to load/parse according to logcat. This results in the third model disappearing from the wallpaper after the preview screen. I need suggestions on reducing burden of this last asset. Are there any better methods for getting this model into the scene? If not I'm afraid I'm going to have to scrap months of work.﻿
![screenshot_2015-08-15-15-51-58](https://cloud.githubusercontent.com/assets/4427024/9290845/89d6ea8c-4367-11e5-987a-28baf50825f5.png)

**Comment by jchristof** [comment]
Did you try:
https://github.com/Rajawali/Rajawali/wiki/Tutorial-04-Optimization

**Comment by jwoolston** [comment]
If I remember correctly, MD5 is an ASCII format. With ASCII formats, you should expect things to be at least 8 times longer than a binary format, just because of the inefficiency in how data is represented. I forget the state, but AWD supports skeletal animation and AwayBuilder would allow you to translate the file. I know we were working on adding it with the help of another user, but I don't remember where we left it.

**Comment by jwoolston** [comment]
Closing as stale.
