### ISSUE TITLE
making rajawaliTextureView transparent?

### ISSUE THREAD

**Issue by cheong12001** [Rajawali/Rajawali#1555]
i would like to ask how can i make the rajawaliTextureView transparent so that i can display my camera view at the back of the 3D objects. Thanks in advance.

**Comment by cuagia** [comment]
try this:
"public void setOpaque (boolean opaque) Added in API level 14

Indicates whether the content of this TextureView is opaque. The content is assumed to be opaque by default."

from: http://stackoverflow.com/questions/18993355/semi-transparent-textureviews-not-working

**Comment by ManuelSchmitzberger** [comment]
@cuagia, unfortunately this doesn't work for.

**Comment by jwoolston** [comment]
This is not possible with a TextureView. Even if you render a transparent clear color, it will be against a white background because of how Android uses texture views in its drawing system. Please read https://github.com/Rajawali/Rajawali/wiki/Using-RajawaliSurfaceView-and-RajawaliTextureView#which-one-to-use
