### ISSUE TITLE
Control animation speed?

### ISSUE THREAD

**Issue by Orbyt** [Rajawali/Rajawali#1564]
I was following the recommended guide to getting a Sphere (earth) scene found here: http://www.clintonmedbery.com/?p=59

Near the end of the tutorial, the scene is animated via:

```java
@Override
    public void onRender(final long elapsedTime, final double deltaTime) {
        super.onRender(elapsedTime, deltaTime);
        earthSphere.rotate(Vector3.Axis.Y, 1.0);
    }
```

How can I control the speed of the earths rotation animation?

thanks.

**Comment by jwoolston** [comment]
This is not so much an animation as it is per frame movement. I make the distinction because Rajawali has an animation system. In anycase, you are provided with a time step and ellapsed time. From there you would calculate the rotation step you desire using a basic kinematic velocity or acceleration equation. depending on your goals.
