### ISSUE TITLE
Memory problems.

### ISSUE THREAD

**Issue by hurzl** [Rajawali/Rajawali#1568]
I get my memory usage growing on each Object3D.setData call. Even when I set the object to null, remove it from currentScene and recreate it with ```new Object3D()```. 
If I use destroy() the Geometry is set to null and crashes on setData afterwards.

Also calling destroy() results in a GL Error:
``` java.lang.RuntimeException: Could not create framebuffer: [1281]: invalid value```

So is there any way to avoid out-of-memory?

**Comment by jwoolston** [comment]
The memory is growing when you call set data because the new data is being appended to the old data. This is the default behavior of Object3D. The crash is because you instructed Rajawali to destroy the object, meaning you would not touch it afterwards. If you want to avoid the problem, either *change* the Object3D data or remove and destroy it and replace it with *an entirely new object*.
