### ISSUE TITLE
Post processing plus color picking

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#1615]
#### Rajawali Version or Branch
`master`

#### Device and Android Version (Please include the complete model number not just 'Galaxy S6', especially if its a Samsung)
N/A

#### Summary
When applying post processing and color picking at the same time as demonstrated in the below snippet, color picking fails to work. Inspection of the color picking frame buffer shows that nothing appears to have been rendered due to some interaction with the post processing system.

#### Steps to Reproduce (Sample code is helpful)
Create a scene with color picking and post processing. The example which demonstrated this is adding the greyscale post processing example code to the ObjectPicking example. In this case the render call is made on the post processing manager and does not pass through to super.onRender()). This lack of pass through could itself be part of the problem.

````java
private final class ObjectPickingRenderer extends AExampleRenderer implements OnObjectPickedListener {

        private DirectionalLight  mLight;
        private Object3D          mMonkey1;
        private Object3D          mMonkey2;
        private Object3D          mMonkey3;
        private Object3D          mMonkey4;
        private ObjectColorPicker mPicker;

        private PostProcessingManager mEffects;

        public ObjectPickingRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            try {
                mPicker = new ObjectColorPicker(this);
                mPicker.setOnObjectPickedListener(this);
                mLight = new DirectionalLight(-1, 0, 1);
                mLight.setPosition(0, 0, -4);
                mLight.setPower(1.5f);
                getCurrentScene().addLight(mLight);
                getCurrentCamera().setPosition(0, 0, 7);

                Material material = new Material();
                material.enableLighting(true);
                material.setDiffuseMethod(new DiffuseMethod.Lambert());

                final LoaderAWD parser = new LoaderAWD(mContext.getResources(), mTextureManager, R.raw.awd_suzanne);
                parser.parse();

                mMonkey1 = parser.getParsedObject();

                mMonkey1.setScale(.7f);
                mMonkey1.setPosition(-1, 1, 0);
                mMonkey1.setRotY(0);
                mMonkey1.setMaterial(material);
                mMonkey1.setColor(0x0000ff);
                getCurrentScene().addChild(mMonkey1);

                mMonkey2 = mMonkey1.clone();
                mMonkey2.setScale(.7f);
                mMonkey2.setPosition(1, 1, 0);
                mMonkey2.setRotY(45);
                mMonkey2.setMaterial(material);
                mMonkey2.setColor(0x00ff00);
                getCurrentScene().addChild(mMonkey2);

                mMonkey3 = mMonkey1.clone();
                mMonkey3.setScale(.7f);
                mMonkey3.setPosition(-1, -1, 0);
                mMonkey3.setRotY(90);
                mMonkey3.setMaterial(material);
                mMonkey3.setColor(0xcc1100);
                getCurrentScene().addChild(mMonkey3);

                mMonkey4 = mMonkey1.clone();
                mMonkey4.setScale(.7f);
                mMonkey4.setPosition(1, -1, 0);
                mMonkey4.setRotY(135);
                mMonkey4.setMaterial(material);
                mMonkey4.setColor(0xff9955);
                getCurrentScene().addChild(mMonkey4);

                mPicker.registerObject(mMonkey1);
                mPicker.registerObject(mMonkey2);
                mPicker.registerObject(mMonkey3);
                mPicker.registerObject(mMonkey4);

                //
                // -- Create a post processing manager. We can add multiple passes to this.
                //

                mEffects = new PostProcessingManager(this);

                //
                // -- A render pass renders the current scene to a texture. This texture will
                //    be used for post processing
                //

                RenderPass renderPass = new RenderPass(getCurrentScene(), getCurrentCamera(), 0);
                mEffects.addPass(renderPass);

                //
                // -- Add a Greyscale effect
                //

                EffectPass greyScalePass = new GreyScalePass();
                greyScalePass.setRenderToScreen(true);
                mEffects.addPass(greyScalePass);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            //
            // -- Important. Call render() on the post processing manager.
            //
            mEffects.render(ellapsedRealtime, deltaTime);
            mMonkey1.setRotY(mMonkey1.getRotY() - 1f);
            mMonkey2.setRotY(mMonkey2.getRotY() + 1f);
            mMonkey3.setRotY(mMonkey3.getRotY() - 1f);
            mMonkey4.setRotY(mMonkey4.getRotY() + 1f);
            //super.onRender(ellapsedRealtime, deltaTime);
        }

        public void getObjectAt(float x, float y) {
            mPicker.getObjectAt(x, y);
        }

        public void onObjectPicked(Object3D object) {
            object.setZ(object.getZ() == 0 ? -2 : 0);
        }

    }
````

**Comment by jwoolston** [comment]
Initial debugging suggests there may be some sort of race condition occurring.

**Comment by rpicolet** [comment]
I've spent most of the last couple of days diving into this, and have some progress to report, but no ultimate cause or fix yet. 

I won't bore you with all of the learning curve that took up most of that time, but I did find one logical error in my code; I was calling `glClearDepthf()` _after_ `glClear()` in `Scene.doColorPicking()`.  However, correcting that oversight did not affect the unreliable picking...

What finally bore some (unripened) fruit was to see if I could reproduce the frame grabs you shared earlier. I'm not sure how you did it, but I inserted a `ScreenGrab` in `ObjectColorPicker.pickObject()` between `glReadPixels()` and `glBindFramebuffer()`. I've attached a typical grab from a standalone color-picking render and a couple from the combined example above:

[standalone](https://cloud.githubusercontent.com/assets/616858/14038151/0fcdbb60-f20a-11e5-9b5a-cf8efe22b72e.png)

[post-processing 1](https://cloud.githubusercontent.com/assets/616858/14038178/7408fb76-f20a-11e5-89d3-e3adab653de5.png)

[post-processing 2](https://cloud.githubusercontent.com/assets/616858/14038449/21450f02-f20e-11e5-9ee6-bc8dc0a5e5c4.png)

Unlike your results, I did not see any plain-white buffers.  Every pick yielded a similar image. At first I thought the post-processing grabs were showing some kind of lighting effect, but then I noticed the straight-line anomalies running across the entire image.  I have no idea what could cause that, other than some kind of memory corruption. 

Regardless, even assuming the transparent regions are (mostly) valid picking colors, it is easy to see why picking would seem random/modal, as the exact picking spot may well be invalid, and the anomalies change from pick to pick on the same object (although the one on the lower left has generally better odds as it is usually not as badly corrupted as the others for some reason).

I also performed one other experiment. I stubbed out the `GreyScalePass`, and just ran the `RenderPass` (with `renderToScreen` true).  That behaved exactly like the unmodified `ObjectPicking` example, with no anomalies, so perhaps the problem is in the interaction between color-picking and the `GreyScalePass`.

I have no idea how memory is organized at the hardware/buffer level, or whether buffer-clearing actually clears every byte in a buffer, etc., and there are probably other explanations for the appearance of the buffer grabs, but it looks like some kind of memory corruption to me at this point.

**Comment by jwoolston** [comment]
> I could reproduce the frame grabs you shared earlier. I'm not sure how you did it, but I inserted a ScreenGrab

I did a `glReadPixles` for the entire frame buffer dimensions and loaded it into a Bitmap conditional on if the debugger was attached. Then I set a breakpoint there and watched this bitmap in the debugger, using AS ability to display the image. See here: https://github.com/Rajawali/Rajawali/blob/1615-development/rajawali/src/main/java/org/rajawali3d/util/ObjectColorPicker.java#L92 for an example of what I am talking about. It does two pixel reads so as to not affect the color picking itself.

As for the images you posted, all that loads are white images so I don't see any of what you see.

The revelations of the stubbed screen pass to me lend support to the idea of gl state being messed up.

> I have no idea how memory is organized at the hardware/buffer level, or whether buffer-clearing actually clears every byte in a buffer, etc.

Organization depends on the device but typically it is system RAM that has been mapped to the GPU. As for clearing, the `glClear` method literally writes the `glClearColor` value to ever pixel in the frame/rebder buffer.

**Comment by rpicolet** [comment]
> See here: https://github.com/Rajawali/Rajawali/blob/1615-development/rajawali/src/main/java/org/rajawali3d/util/ObjectColorPicker.java#L92 for an example of what I am talking about. 

Yeah, that's essentially the same as what I did, except I wrote the grabs to files using the `ScreenGrab` class instead of using the debugger, and I grabbed after the pixel buffer read instead of before...

> As for the images you posted, all that loads are white images so I don't see any of what you see.

Not sure why; perhaps your viewer is using white as the background color so the transparent areas don't show up? On my Mac, they display well/identically in the Finder, Preview, and when I just click the links here in Firefox (all three probably use the same underlying system call...)

> As for clearing, the glClear method literally writes the glClearColor value to ever pixel in the frame/rebder buffer. 

Well now.  

Based on that,  I tried grabbing the framebuffer in `Scene.doColorPicking()` both right after `glClear()` (to see the cleared buffer) and right before `ObjectColorPicker.pickObject()` (to see the fully rendered buffer) ... 

[doColorPicking w: grabs.txt](https://github.com/Rajawali/Rajawali/files/190000/doColorPicking.w.grabs.txt)

And everything worked!!  Clean buffers after clearing, clean renders before picking, and reliable (but slow) picking. Suspecting that changed timing due to the grabs was masking the problem,  I then backed out the second grab, leaving just the grab after clearing, and it still worked.  But when I backed out the grab after clearing, it was broken again!

Assuming I haven't botched something in my testing technique, then it seems like either
* the buffer clearing is not completing synchronously on the `glClear()` call, or
* something in another thread/process (low-level frame swapping?) is trashing the native buffer memory.

Not sure where to go from here.  Please challenge anything that doesn't make sense to you.
Any other ideas/suggestions?

**Comment by jwoolston** [comment]
Both of your assessments I hadn't considered directly, but the thought of a threading type issue did come to mind so this is an interesting possibility. I will need to think through it. The issue is occurring in a Frame buffer so this seems like it shouldn't be the case, but the behavior is inescapable. I will have to ponder on the issue. Perhaps a few beers are in order, I just brought home a box from your neck of the woods from Speakeasy Brewing.

**Comment by rpicolet** [comment]
Nice, enjoy!! :beers: Sometimes pondering is best approached with an improved attitude!

**Comment by rpicolet** [comment]
So, I've tried a few more experiments today, and need to amend my prior results: the `ScreenGrab`s I inserted into `Scene.doColorPicking()` _do_ significantly increase the success rate, but there are still some small "straight-line" anomalies in the rendered buffers that cause infrequent picking failures.  Here is a typical rendered grab (assuming you can view it somehow):

[pickerbuffer2](https://cloud.githubusercontent.com/assets/616858/14062974/62048a18-f371-11e5-928a-32734c7074b2.png)

To find out if there was some particular aspect of the `ScreenGrab` that was responsible for masking/reducing the problem, I tried lexically introducing "functional chunks" of `ScreenGrab` code one at a time after `glClear()`, effectively varying how much processing/delay occurs before drawing the actual elements. In general, it _seemed_ like corruption is reduced and picking reliability improves the longer the actual color-picking render is delayed.

To test that idea out, I then tried moving the invocation of `doColorPicking()` to the very end of `Scene.render()` instead of the very beginning.  Magically, it worked.  Clean everything.

That is very unsatisfying as a solution, of course, since it doesn't really identify the cause of the original problem.  Anyway, I'm open to your direction on whether to just accept the magic solution or keep looking.  I don't think basing the response to the picking request on the state of the next frame - rather than the prior - will be noticeable...

**Comment by rpicolet** [comment]
Happy Rabbit Day  :rabbit: 

I don't _think_ either of these could cause the symptoms we are seeing, but...

One, I noticed that `EffectPass.setShaderParams()` calls:
```
		mMaterial.bindTextureByName(PARAM_TEXTURE, 0, mReadTarget.getTexture());
```
which adds the read target texture to the material's `mTextureHandles` in the first frame, and binds it to the `GL_TEXTURE_2D` target of `GL_TEXTURE0` every frame.  But that texture doesn't appear to ever be unbound, as `Material.unbindTextures()` only unbinds the textures that have been added to `mTextureList`...

Two, I noticed that ScreenQuad flips its texture coordinates right-to-left, and couldn't figure out why (even though it apparently works...)

Thought I would point these out just in case.

**Comment by jwoolston** [comment]
> Happy Rabbit Day

Happy Rabbit Day indeed!

> Two, I noticed that ScreenQuad flips its texture coordinates right-to-left, and couldn't figure out why (even though it apparently works...)

Yea I'm not certain what the reasoning for this is. @MasDennis would have to weigh in there.

> To test that idea out, I then tried moving the invocation of doColorPicking() to the very end of Scene.render() instead of the very beginning. Magically, it worked. Clean everything.

This is interesting, because its also how it used to work which was compatible with post processing. Seems like a viable short term solution, but also seems like we should be able to get it to work upfront.  Can you confirm moving it to the end works fine with the screen grab code removed?

The timing sensitivity here seems to add further evidence for the corruption theory, though I'm not convinced the texture binding is the culprit. The issue point out is a problem for sure, and you should create a ticket for it, however the color picking uses its own frame buffer object and unless the read target backing texture is somehow pointing to the same texture id as the color picking frame buffer, they wont affect each other.

Im thinking at this point profiling the gl calls will be the only resolution. I have tried using the GPU debugging library Google includes with the build tools but it seems to always crash so I am not sure whats going on there. I think, but cant remember if the `DebugRenderer` will log all GL calls. We could also turn on logcat gl call debugging, the only problem there is it logs everything, including system draw calls.

**Comment by rpicolet** [comment]
> This is interesting, because its also how it used to work which was compatible with post processing. 

Lexically, yeah, the old `createColorPickingTexture()` call was at the end of Scene.render() but it then recursed to do the visible render, so execution order was still color-picking first, which I didn't think to change when I updated the feature...

> Can you confirm moving it to the end works fine with the screen grab code removed?

Confirmed.  At least on my old S3.

> ...though I'm not convinced the texture binding is the culprit.

Yeah, me either.  I'm just digging for dirt.

>The issue point out is a problem for sure, and you should create a ticket for it,

Done.

> the color picking uses its own frame buffer object and unless the read target backing texture is somehow pointing to the same texture id as the color picking frame buffer, they wont affect each other.

Yeah, I agree it seems the buffers are configured/managed OK

I keep going back to when the screen grabs are corrupt.  It just seems like, if it's long enough after the end of the prior frame, there is no corruption. As the clearing and/or rendering run closer and closer to the end of the prior frame, they seem to get more and more corrupted. There are also at least two distinct patterns to the corruption; first is some horizontal line segments around 10 pixels thick if glClear() runs right away (always the same exact pattern; these are what made the color picking fail occasionally).  Then if there is no screen grab (or RenderPass?) to delay things, there seems to be some kind of pseudo-random reflection and/or transparency inversion of portions of the rendered monkeys across vertical lines, and/or overlays with transparency-inverted monkeys (which causes the high failure rate for color picking).  

I have yet to see a completely white buffer after any color-picking element draws, only after a delayed clear. Have you had time/been able to replicate any of my screen grabs?  If not, maybe there is actually a hardware/GPU issue...

If we can't identify a correctness issue in the setup/teardown of the GL state in one or more of the render passes, I have to wonder if we might be running up some kind of underlying hardware/timing constraints.  I ran a quick FPSListener, and it reported 62+ fps, but perhaps only color-picking frames cross some kind of threshhold due to the extra render, and those don't happen enough to affect the average?

I would still prefer for it to be some kind of oversight on my part, as that would be a good explanation and an easy fix.  One at a time, I will try adding back in each of the steps/GL calls I optimized out of the color-picking render.  That's essentially how I decided I could remove them in the first place, but I wasn't running post-processing then.

>  We could also turn on logcat gl call debugging, the only problem there is it logs everything, including system draw calls.

I tried using the OpenGL Trace tool in Android Device Monitor a couple days ago, and was able to capture traces and see all of the GL calls in order, but I wasn't sure what I was looking for besides that...  I'll try installing the GPU debugging library too.

**Comment by rpicolet** [comment]
OK, good news! You were right all along, it was incorrect GL state, and of course it was my code.

In Scene.doColorPicking(), I was failing to set the depth mask true prior to glClear(). That's it.  Sorry for wasting your time with all the red herrings about timing/threading. At least I learned a lot about Raj internals!

PR on the way.

**Comment by jwoolston** [comment]
> In Scene.doColorPicking(), I was failing to set the depth mask true prior to glClear(). That's it. Sorry for wasting your time with all the red herrings about timing/threading. At least I learned a lot about Raj internals!

Hardly a waste of time. Its helpful on my end as well to keep me thinking about new things. Happy to hear you got it figured out. Get yourself a well deserved beer sir! :beers:

**Comment by rpicolet** [comment]
> to keep me thinking about new things...

Like you don't get enough opportunities... :wink: 

>Get yourself a well deserved beer sir! 

What a delightful idea; think I'll do just that.
