### ISSUE TITLE
FeatureRequest: OnObjectPicking Failure

### ISSUE THREAD

**Issue by conect** [Rajawali/Rajawali#1640]
It would be nice to have an additional callback function, which tells the user, that the object colorpicking failed and there's no picked object. Or is this functionality already implemented and I don't know how to use it. Currently I set a timestamp and wait 200ms if no object was selected i know the picking failed.

Regards conect.

**Comment by jwoolston** [comment]
Seems reasonable.

**Comment by rpicolet** [comment]
I would like to take this on if that is OK with the team.  Not only is it a good feature, it obviates the need to ever render the Skybox for color-picking (which is the only way I could get the same result way back in v0.9, and I forgot that was the reason).

**Comment by ToxicBakery** [comment]
I would prefer if this was a 2nd interface such that it can be optionally implemented as I imagine most use cases do not care to know that an object was not found.

**Comment by rpicolet** [comment]
I think there are several uses for knowing the user touched the screen somewhere other than on a registered `Object3D` (controlling an animation, starting a swipe gesture that rotates a group of `Object3D`'s, popping up a scene-level context menu/action mode on a long press, etc.). I do things like that in my app, which is why I (currently) need to register a skybox for picking.  But perhaps we don't need to debate use cases.

For example, if no registered `Object3D` is picked, perhaps `onObjectPicked()` can just return either a null or - maybe even better - a canned/placeholder/flag "BACKGROUND" `static final Object3D` (to reduce the chance of breaking any existing apps that aren't expecting a null, although default logic might still get triggered for an "unknown" object)?  If either of those approaches are acceptable, then the current interface (and documentation of the return value when no registered object is picked) is all that's needed.

**Comment by rpicolet** [comment]
> perhaps onObjectPicked() can just return either

can just _pass_ either...

**Comment by rpicolet** [comment]
... which suggests maybe also changing the return type to boolean to indicate success/failure? That would force compile failures so existing apps would be informed of the change... ?

**Comment by jwoolston** [comment]
Lol, probably should have checked for updates before doing this....reopening for alterations.

**Comment by jwoolston** [comment]
@rpicolet 

> I would like to take this on if that is OK with the team

Not a problem, just make sure you unwind the changes I made rather slap handedly.



> to reduce the chance of breaking any existing apps that aren't expecting a null,

Don't worry about this. We are in an API change and no app is going to automatically get the updated Rajawali. 

What I did was add a method to the interface. I had considered returning null, but I don't like making contracts depend on checking for null....its verbose, sloppy and generally feels dirty. Feel free to handle it any other way you prefer though and we can take a look.

**Comment by rpicolet** [comment]
LOL, I figured we crossed in the mail. I just offered to save you some time. I'm perfectly happy with your changes if you are (I've already incorporated them in my app ;-) ). Above, I was just trying to address Ian's concerns about requiring apps to implement a second method, but I'm pretty convinced most non-trivial apps will need to deal with a non-pick in some way, and I agree with avoiding null.  I'll leave it to Ian if he wants to use a different approach though...

**Comment by jwoolston** [comment]
@rpicolet Thanks. Feel free to take on any of the other tickets! I'm still having a hard time getting color picking and post processing to play nice. It should be possible to just use the render call from post processing since the color picking pass will automatically be triggered. It does indeed call, but the color picking pass always renders blank. My current theory is the post processing manager leaves the gl state messed up in some way after the first pass, meaning we need to figure out what GL State calls we are missing from the color picking setup.

**Comment by rpicolet** [comment]
>  Feel free to take on any of the other tickets!

Be careful what you ask for...  I can dig really deep holes, so keep me on a short leash.

> but the color picking pass always renders blank

The thing is, color picking kinda works as if the scene was rendered correctly (i.e. `RenderPass` model transformations - the only thing really re-used from the prior frame by the color-picking pass - seem correct), and I don't understand how any picking could be happening at all if the color-picking frame buffer is completely blank, yet it _does_ respond to some touches.  

To me, it really seems like it is purely a post-processing rendering (`EffectsPass`/`ScreenQuad` handoff?) issue, since I was able to add `mMonkey1` from the `ObjectPicking` example to the `GreyScale` example, and it showed up reflected across the X-axis from where it should have been (lower left instead of upper left, and upside down). Maybe something with a coordinate that needs `y = viewport.height-y`... Just brainstorming...

I'll take another look at the code, see if I can ask some obvious questions.

**Comment by jwoolston** [comment]
> I don't understand how any picking could be happening at all if the color-picking frame buffer is completely blank, yet it does respond to some touches.

In those rare cases, the buffer isn't blank.

The flipping was just due to how the texture coordinates for screen quads worked. Ive already corrected those texture coordinates. Another look is always appreciated, otherwise I'll get to it whenever. Trying to nail down these memory/lifecycle issues once and for all.

**Comment by rpicolet** [comment]
Hmm.  I just tried adding a mMonkey1 to GreyScale again on master, and she's still rendered in the lower left instead of upper left,  and upside down...

**Comment by jwoolston** [comment]
It's on a working branch, not in master yet.

**Comment by rpicolet** [comment]
Ah, nevermind...

**Comment by jwoolston** [comment]
See the 1615-development branch if you are interested

**Comment by conect** [comment]
Thanks a lot for your fast realisation of this feature request you're the best!!!
