### ISSUE TITLE
customize StreamingTexture

### ISSUE THREAD

**Issue by WeixiangZhang** [Rajawali/Rajawali#1723]
#### Rajawali Version or Branch
V1.1.337

#### Device and Android Version
Android 4.4+

#### Summary
The StreamingTexture can not meet my need. 
But I can't extend ATexture to implement my own SteamingTexture, because the four abstract methods add(), remove(), replace(), reset() in ATexture are private. 

Can you set the methods to public instead of private?

#### Steps to Reproduce
None

#### Trace or Log Output
None

**Comment by jwoolston** [comment]
No. This was done for a reason and exposing them would provide an opportunity for users to break their implementation, leading to issues being created because someone tried something not realizing the implication on the engine. We try hard (as all library developers do/should) to expose only the methods people will need, leaving engine internal methods to do as they will. Perhaps a better way to go about this is to create an issue asking for help in getting the streaming texture to suit your needs, especially if it makes things more flexible and results in improvements to the engine. In lieu of that, you are always free to clone the repo and make whatever changes you desire.
