### ISSUE TITLE
CubeMapTexture mirrors bitmap

### ISSUE THREAD

**Issue by odin-** [Rajawali/Rajawali#1884]
I am using Rajawali 1.1.777

When I use `CubeMapTexture` and bitmaps the bitmap is mirrored:

```
Material m = new Material();
m.setColor(0);
CubeMapTexture t = new CubeMapTexture("board_textures_"+r+"_"+c,new Bitmap[]{mBoardBg, mBoardBg,, mBoardBg, mBoardBg, bitmap, mBoardBg});
RectangularPrism p = new RectangularPrism(tileSize, tileSize, tileSize, true);
try {
   m.addTexture(t);
} catch (ATexture.TextureException e) {
   Log.d(TAG, "Texture error", e);
}
p.setMaterial(m);
getCurrentChild.addScene(p);
```

`bitmap` is displayed mirrored.

What am I missing? Is this an intended "feature" of OpenGL/Rajawali?

**Comment by contriteobserver** [comment]
Since the final parameter in `new RectangularPrism(tileSize, tileSize, tileSize, true)`, the texture is assumed to be a Sky Box, so the expectation is that the camera is inside the prism. Viewed from the outside, the bitmap will appear mirrored.

When creating a prism with six textures that is to be viewed from the outside, best to model it as six child planes.

**Comment by odin-** [comment]
Thank you for the explanation!
