### ISSUE TITLE
Using CubMapTexture on RectangularPrism fails

### ISSUE THREAD

**Issue by odin-** [Rajawali/Rajawali#1905]
Rajawali 1.1.777

I want to have six different textures on a `RectangularPrism`. If I enable skybox and use `CubeMapTexture` it does not work if the texture bitmaps has different size. Since I am using a `RectangularPrism` I want to have different sizes on different textures as it's a rectangle.

(variable `bitmap` in the example is 128x128 px)

        Bitmap b2 = Bitmap.createBitmap(bitmap, 0, 0, 64, 128);
        Bitmap b3 = Bitmap.createBitmap(bitmap, 0, 0, 128, 64);
        Bitmap[] textures = {b2, b2, b3, b3, bitmap, bitmap};
        CubeMapTexture texture = new CubeMapTexture("bg_" + id, textures);
        Material material = new Material(true);
        material.setColor(0);
        texture.isSkyTexture(true);
        try {
            material.addTexture(texture);
        } catch (ATexture.TextureException e) {
            Log.d(TAG, "Texture error", e);
        }
        RectangularPrism prism = new RectangularPrism(s, s, s/2, true);
        prism.setMaterial(material);
        return prism;

PS: I don't want to build the RectangularPrism using 6 Plane objects. I have a a lot of objects currently and when I tried using 6 Planes instead of the RectangularPrism it at least seemed like I lost smoothness during object rotation.

**Comment by jwoolston** [comment]
Open GL does not allow you to create a cube map of different sizes for each face. In fact, this would be contrary to the very definition of a cube map - cube implies all faces are identical in size.

**Comment by odin-** [comment]
OK thanks. I guess that's my problem: If I have a Rectangle

    RectangularPrism prism = new RectangularPrism(s, s, s/2, true);

And have a CubeMapTexture the front and back face (positive/negative Z) gets distorted. 

What I want to have is a Texture on each face that displays correctly.

**Comment by odin-** [comment]
I'll open another issue with a new more clear question. Thanks.

**Comment by jwoolston** [comment]
There is no way to do this with primitives other than using 6 planes and 6 textures. If you want to build your own custom geometry, you can specify texture coordinates into either a custom texture which combines the six face textures into 1 or a texture atlas effectively doing the same, but either way you will need to generate your rectangular prism's texture coordinates yourself....what Rajawali generates will not achieve what you desire. Anytime you start talking about custom objects like this, you enter the realm of artist specified material parameters. Most 3d art tools allow you to texture the geometry in 3 dimensions and then "unwrap" the texture into a 2d file with appropriate texture coordinates (often it will look distorted because of the 3D to 2D mapping).
