### ISSUE TITLE
Question: Object3D with bones (Skeletal)

### ISSUE THREAD

**Issue by kovac777** [Rajawali/Rajawali#1957]
Hello guys! I have the question about support Object3D with bones. 
Can I move this object when touched to the junction of the bones?? Or may be you have any sugguestions aboit how implement this feature??

**P.S** _Very much thanks for this framework!!! You are COOL!!!_

**Comment by AnthonyMarc** [comment]
Hi! I'll try to give you an answer: you must use the **MD5** file format for the **skeletal animations**. If your model is created with Blender you can use the Katsbits MD5 exporter plugin here: **https://www.katsbits.com/tools/**
More infos about implementing MD5 skeletal animation in this rajawali wiki:
**https://github.com/Rajawali/Rajawali/wiki/v0.9-Tutorial-29-Skeletal-Animation**

**Comment by kovac777** [comment]
thx for your answer! I know how I can make MD5 animations, but I need move only part (1 bone) of 3d model when touch to it

**Comment by AnthonyMarc** [comment]
Make the animation using a software like Blender and play it when you touch the models. See
**https://github.com/Rajawali/Rajawali/wiki/v0.9-Tutorial-12-Object-Picking**
as reference for the realization, or look at the examples in the rajawali master folder.

**Comment by kovac777** [comment]
I need to move the crane in a certain range. The crane consists of three bones. The way which you offered does not fit

**Comment by AnthonyMarc** [comment]
Don't know if you can move the bone directly, but I think not at the actual state. All that I can suggest you is to create the animations you want to achieve and to trigger it using buttons or reading the finger position on screen or the movement for example.

**Comment by rpicolet** [comment]
Not sure if I understand your goal completely, but it seems like you could compose an object3D model that directly reflects the crane components and structure, e.g., make base of the crane the root object, the first arm segment a child of the root, the second a child of the first (transposed by the arm length), etc.  That would provide the composed transformations exactly like a real robot arm/crane. To actually select joints (as opposed to arm segments that meet at the joint) there would need to be some object (e.g. a simple sphere centered on the joint) that could be used for object picking (which could also serve as containers for the next arm segment. They could be "visible" but transparent if you don't want them to actually show up, or semi-transparent, and as big or small as you want.  Those could then be used for touch-and-drag controls or to start/stop rotation animations at that joint or whatever makes sense.  This would also allow you to model the constraints at each joint for range of motion, speed, acceleration, or however fancy you need to get...  Hope this helps!

**Comment by kovac777** [comment]
Thanks for your answer, but in connection with my English I understood only part of your answer, could you, as an example, show the base code

**Comment by rpicolet** [comment]
I'm sorry, I didn't really explain the idea very well, but I'm also not sure what you are seeing, so perhaps you can post some of your code. I failed to say that there needs to be a parent Object3D for each joint, with its child arm segment translated so as to "attach" it at one end to its parent joint, and with a child/joint container (for any nested objects) translated to the other end of that segment.  Then rotating a parent joint object, (not the child arm segment object itself) should rotate all nested objects as a group, e,g. :

```
Scene.init() {
Object3D base = new Object3D();
...
Object3D joint1 = new Object3D();
...
base.addChild(joint1);
joint1.translate(<offset of joint1's origin from base origin>);
Object3D arm1 = new Object3D();
...
joint1.addChild(arm1);
arm1.translate(<offset of arm1's origin from joint1 origin>);
Object3D joint2 = new Object3D();
...
joint1.addChild(joint2);
joint2.translate(<length of arm1>);
Object3D arm2 = new Object3D();
...
arm2.translate(<offset of arm2's origin from from joint2 origin>);
Object3D joint3 = new Object3D();
...
joint2.addChild(joint3);
joint3.translate(<length of arm2>);
Object3D endEffector = new Object3D();
...
endEffector.translate(<offset of endEffector's origin from joint3 origin>);
...
// etc.
}
```
Clearly, you will also have to apply initial rotations to orient the arm segments and joints to reflect your model constraints. I hope this makes more sense...  

Your user interaction design then somehow has to select a joint and control its rotation via gestures and/or animations and/or frame callbacks. I'd be leery of using arm segment touch/drag to select/control the joint if arms may sometimes be oriented perpendicular to the screen or somehow hidden, which is why I suggested perhaps using oversize and/or semi-transparent child Sphere objects centered on each joint as touch targets. Perhaps more simply, maybe just use some combination of 2D buttons and simple screen swipes and forego object selection altogether. But you may well have a much better idea for how to proceed. Be careful about UI vs GL threads!

**Comment by kovac777** [comment]
Thx for your answer! Now I understand what you meant, but how can I get length/offset? And I did not find `translate()` method

**Comment by rpicolet** [comment]
Yeah, duh, I meant `setPosition()` not `translate()`.  

You will probably have to get the lengths/offsets to use from manually analyzing the 3D model objects themselves; I don't really see a good way to do it at runtime.  

And all of this assumes the relevant crane components are modeled as separate objects in the first place, so that may be a challenge depending on how the crane is currently modeled...  You will need to be able to load the modeled base/arm segments/endEffector/etc. as separate objects.

**Comment by jwoolston** [comment]
Closing this issue as resolved/stale. Please let us know if issues persist.
