### ISSUE TITLE
Model seems transparent

### ISSUE THREAD

**Issue by MDPtechDeveloper** [Rajawali/Rajawali#2011]
I've problem with Rajawali because whe i try to render my model it seems trasparent like this: 
 ![screenshot_20171106-154238](https://user-images.githubusercontent.com/33424616/32446950-d7a91a4e-c30a-11e7-8497-9e53ddf614ad.jpg).
When on blender it look like this:
![immagine](https://user-images.githubusercontent.com/33424616/32446948-d78a0c76-c30a-11e7-9194-a5bbfacdfa91.png).
Someone that know why it happens? 
Someone that already had this problem?
In my code i don't write much, only load model, add to a container and add it to Rajaview with some lights.

**Comment by contriteobserver** [comment]
`LoaderOBJ.parse()` only handles triangles and quads. The most common cause of this issue is a model containing faces with more that 4 sides. One way of addressing this issue is to select the object, press `Tab` to go into `Edit mode`, press `CTRL-T` to triangulate all the faces, and then press `ALT-J` to convert Tris to Quads, and then export the model as usual.

**Comment by MDPtechDeveloper** [comment]
It not works yet, can you also tell me what check when export model on blender?

**Comment by MDPtechDeveloper** [comment]
I've resolved it flipping normlas and set all part that looks transaprent to "inside".
