### ISSUE TITLE
Loading 14mb .obj file

### ISSUE THREAD

**Issue by augmentedreality01** [Rajawali/Rajawali#2059]
#### Rajawali Version or Branch
org.rajawali3d:rajawali:1.1.337@aar

#### Device and Android Version
Samsung S7
Android 8.0.0

#### Summary
Loading an 14mb .obj file producing no visual output and the following error message.

#### Trace or Log Output
07-13 15:20:03.409 26806-26843/com.example.olp8fe.a3dof_model_visualization E/Rajawali: Getting location of uniform: uNormalMatrix returned -1!
    Getting location of uniform: uModelMatrix returned -1!
    Getting location of uniform: uModelViewMatrix returned -1!
    Getting location of uniform: uTime returned -1!

**Comment by contriteobserver** [comment]
The error messages are not revealing, see #1699 

`LoaderOBJ` only loads a subset of OBJ files. It fails quietly if faces have more than four sides, also, parsing NURBS surfaces or per face textures is not supported. You will have to simplify the feature set of the model for Rajawali to display it.

**Comment by augmentedreality01** [comment]
Thanks for your answer!
If i cannot simplify the texture, which 3d framework are you recommending for loading complex OBJ files?

**Comment by contriteobserver** [comment]
Try importing your OBJ file into blender, triangulating all the faces, and if the model still look right, export the result as a derivative OBJ file. Then try loading the derived file into Rajawali.

If more flexible file loading is required, one might want to look at loading Rajawali with the [Open Asset Import Library](https://github.com/assimp/assimp) instead of `LoaderOBJ` to parse the files.

**Comment by ToxicBakery** [comment]
This issue appears to be resolved, please reopen if that is not the case.
