### ISSUE TITLE
how to create an ortho Camera?

### ISSUE THREAD

**Issue by hariedo** [Rajawali/Rajawali#217]
I have not figured out the Camera class enough to know how to set up an orthographic (non perspective) matrix.  Most 3d libs would have some common matrix helpers like setOrtho(scale) or lookAt(x,y,z,up) but I don't mind if I have to set up a matrix from scratch.  The setProjectionMatrix() only takes two integers though.

**Comment by kiranpradeep** [comment]
@MasDennis 
 1.  Most  methods of `Camera.java` are guarded by `mFrustumLock` even though a comment in `RajawaliScene.java` mentions that  `Camera` should be used only by GL thread. So, is that `mFrustumLock` guard necessary ?
 2.  If it is necessary, `OrthographicCamera::setProjectionMatrix` is not guarded by the same. Is this intentional ?
