### ISSUE TITLE
getBoundingSphere  ignores scale factor 

### ISSUE THREAD

**Issue by madhawa-se** [Rajawali/Rajawali#2200]
#### Device and Android Version
Rajawali version 1.1.517

#### Summary
I'm trying get radius after scaling object but i'm getting same value for radius.
BoundingSphere keep unchanged even after scaling 3D object.Is there any way to get correct bounds after scaling ?

#### Steps to Reproduce
    double scaleFactor =2;
    BoundingSphere bounds = xGeometry.getGeometry().getBoundingSphere();
    double radiusBefore = bounds.getRadius(); // radiusBefore is 2.0
    xGeometry.setScale(scaleFactor,scaleFactor,scaleFactor);
    double radiusAfter = bounds.getRadius(); // radiusAfter is 2.0

**Comment by contriteobserver** [comment]
`ATransformable3D.setScale()` changes the object model matrix, not geometry.
So it is expected that `Geometry3D.getBoundingSphere()` remains unchanged.

To get correct bounds radius after scaling, try:
```
double radiusAfter = bounds.getRadius() * obj.getScale().length();
```
note that `obj.getScale().length()` is not expected to be 2, because `ATransformable3D.setScale()`  doubled the height, width, and length, so radius is `Math.sqrt(x * x + y * y + z * z)`

**Comment by madhawa-se** [comment]
thanks it worked.
