### ISSUE TITLE
Cannot load .obj or .3ds

### ISSUE THREAD

**Issue by ccoffey** [Rajawali/Rajawali#328]
Guys,

I am still have zero luck with loading my own models.
I have tried exporting both .obj and .3ds from 3dsMax Studio 2013.

Here are my files.
.3ds: https://dl.dropbox.com/u/11502389/arduino4_3ds
.obj: https://dl.dropbox.com/u/11502389/arduino.zip

The .obj file parses correctly (zero errors, its just invisible).
The .3ds throws an exception.

Regards,
Cathal

**Comment by huylv177** [comment]
I got same problem, it can not show my 3d model. Here is my model https://www.dropbox.com/s/7lwt9m3tcgsowz0/axis.rar?dl=0
![image](https://cloud.githubusercontent.com/assets/7688070/17325544/5b42166c-58d6-11e6-931a-32952a44d825.png)

**Comment by power7714** [comment]
@huylv177 I'm going to take a look at your model right now. I'll see if I can get it working and then upload the working version for you if I'm successful.

**Comment by power7714** [comment]
@huylv177 Here's your model. [Click Here](https://www.dropbox.com/s/tpd4j4kcuy2hlb8/axisworking.rar?dl=0). I works and can be seen in Rajawali. Looks like you exported it with a different 3d program other than the recommended blender software. I opened your model with Cinema4D. Added color to each pole and named each pole "poleOne, etc." so you can access them individually. Your center pivot point is off center. Your model is negative on the X and Y axis so it isn't center. I left that alone because I wasn't sure if you intended that or not. With its current positioning, you would have to move the camera to the left along the X axis to see it fully. I saved your model as an fbx and imported into blender. Then exported as a obj file with the recommended settings. I personally only use blender to export my model for use with rajawali. I'm not familiar with the 3d software you used but your model came out flipped 180°. Even in Rajawali. If you would like, I can center your model on the center world axis and position it the way you  intended. Just let me know.

**Comment by huylv177** [comment]
Thank you, i have tried blender and all the new models exported from blender are work fine. The previous model i used 3D Builder (preinstall on win10), maybe it was built in different form.
