### ISSUE TITLE
Set alpha property correctly

### ISSUE THREAD

**Issue by ghost** [Rajawali/Rajawali#444]
How we can change the alpha on a plane?

My plane is a 2D text, so I just cutting out my black pixels from the background in a custom Material.

Than I tried to:

```
    mHelloPlane.setBlendingEnabled(true);
    mHelloPlane.setDepthTestEnabled(true);
    mHelloPlane.setBlendFunc(GLES20.GL_ONE, GLES20.GL_ONE_MINUS_SRC_ALPHA);
    mHelloPlane.setColor(0xaaff0000);
```

I d like to add an alpha to this plane, but this is not working.

**Comment by mukulabdagiri** [comment]
Apologies for re-opening a stale topic, but how did you manage to solve the problem?
I am having the same issue with my custom fragment shader. 
I am fading the texture by manipulating alpha values using setColor().
It works fine, but some times, the screen goes black for a few seconds after resuming my Android device from sleep and then works normally as expected.
You are right that the problem is here:
" gl_FragColor = texture2D(uDiffuseTexture, vTextureCoord) * vColor;\n" +
How did you manage to solve it?

Thanks,
Mukul
